### ISSUE TITLE
给你计算方法

### ISSUE THREAD

**Issue by Noo6coder** [ClaretWheel1481/GenshinImpact-Wish-Simulator#1]
原神UP池的五星出金概率，以0.6%为基准，在第73抽之前不变，第73抽之后每一抽出金的概率提升6%，直到90抽的时候为100%。

四星角色的概率也是同理，第1-8发初始概率为6%，是在第9发开始提升，到第10发的时候就能达到100%。因此虽然说10连保底四星，其实在第9发出四星的概率就已经不低了，大多数玩家也是在第9发出的四星。

——摘自https://mp.weixin.qq.com/s/p9udsNEA3we7Bc6xFCVy-A

**Comment by ClaretWheel1481** [comment]
Salute
